paths:
  /api/products:
    get:
      summary: Get all the products from the Database
      tags:
        - Products
      responses:
        "200":
          description: Se obtienen todos los productos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: Error interno del servidor
    post:
      summary: This endpoint creates a product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/addProduct"
      responses:
        "200":
          description: Producto creado correctamente
  /api/products/{pid}:
    get:
      summary: Get only one product by ID
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: id del producto que se quiere buscar
        schema:
          type: string
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: Error interno del servidor
    put:
      summary: Update product by ID
      tags: 
        - Products
      parameters: 
      - name: pid
        in: path
        required: true
        description: id del producto que se quire actualizar
        schema:
          type: string
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct"
      responses:
        "200":
          description: Producto actualizado correctamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor
    delete:
      summary: Delete product by ID
      tags: 
        - Products
      parameters: 
      - name: pid
        in: path
        required: true
        description: id del producto que se quire eliminar
        schema:
          type: string
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#components/requestBodies/deleteProduct"
      responses:
        "200":
          description: Producto eliminado correctamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor


components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID autogenerado por MongoDB
        title: 
          type: String
          description: Nombre del producto
        description: 
          type: String
          description: Descripcion del producto
        price: 
          type: Number
          description: Precio del producto
        code: 
          type: String
          description: Codigo del producto
        stock: 
          type: Number
          description: Stock del producto
        category: 
          type: String
          description: Categoria del producto
        status: 
          type: Boolean
          description: Estado del producto
        owner: 
          type: String
          description: Dueño del producto
      example:
        _id: ObjectId('1234')
        title: Iphone 15 Pro 
        description: Cellphone 15 Pro bran Apple
        price: 2000
        code: 13456
        stock: 300
        category: Cellphones
        status: true
        owner: admin



  requestBodies:
    createUser:
      type: object
      properties:
        title: 
          type: String
          description: Nombre del producto
        description: 
          type: String
          description: Descripcion del producto
        price: 
          type: Number
          description: Precio del producto
        code: 
          type: String
          description: Codigo del producto
        stock: 
          type: Number
          description: Stock del producto
        category: 
          type: String
          description: Categoria del producto
        status: 
          type: Boolean
          description: Estado del producto
        owner: 
          type: String
          description: Dueño del producto
      example:
        _id: ObjectId('1234')
        title: Iphone 15 Pro 
        description: Cellphone 15 Pro brand Apple
        price: 4000
        code: 13456
        stock: 100
        category: Cellphones
        status: true
        owner: admin'